version: "3"
services:
  mariadb:
    image: jc21/mariadb-aria:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - drupal_network
    restart: unless-stopped
    volumes:
      - /portainer/Files/AppData/Config/drupal/database:/var/lib/mysql

  druapl:
    container_name: drupal
    hostname: drupal
    image: drupal:latest
    networks:
      - drupal_network
    ports:
      - 4080:80
    restart: unless-stopped
    volumes:
      - /portainer/Files/AppData/Config/drupal/modules:/var/www/html/modules
      - /portainer/Files/AppData/Config/drupal/profiles:/var/www/html/profiles
      - /portainer/Files/AppData/Config/drupal/themes:/var/www/html/themes
      - /portainer/Files/AppData/Config/drupal/sites:/var/www/html/sites2
    depends_on:
      - mariadb

networks:
  drupal_network:
