version: "3"
services:
  mariadb:
    image: linuxserver/mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}
    networks:
      - gitea-mariadb_network
    restart: unless-stopped
    volumes:
      - /portainer/Files/AppData/Config/Gitea/Mariadb:/config

  gitea:
    container_name: gitea
    hostname: gitea
    image: gitea/gitea:latest
    environment:
      GITEA__database__DB_TYPE: mysql
      GITEA__database__HOST: 'mariadb':3306
      GITEA__database__USER: ${DATABASE_USER}
      GITEA__database__PASSWD: ${DATABASE_PASSWORD}
      GITEA__database__NAME: ${DATABASE_NAME}
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}
    networks:
      - gitea-mariadb_network
    ports:
      - 8124:3000      
      - 222:22      
restart: unless-stopped
    volumes:
      - /portainer/Files/AppData/Config/Gitea/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - mariadb

networks:
  gitea-mariadb_network:
