version: '2'
services:
  kanboard:
    image: kanboard/kanboard:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /portainer/Files/AppData/Config/Kanboard/data:/var/www/app/data
      - /portainer/Files/AppData/Config/Kanboard/plugins:/var/www/app/plugins
      - /portainer/Files/AppData/Config/Kanboard/ssl:/etc/nginx/ssl
volumes:
  kanboard_data:
  kanboard_plugins:
  kanboard_ssl: