version: "3.7"
services:
  app:
    image: nodered/node-red:latest
    container_name: node-red
    environment:
			NODE_RED_CREDENTIAL_SECRET: ${NODE_RED_CREDENTIAL_SECRET}
			TZ: ${TZ}
      DB_MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - node-red-data:/data
    ports:
      - 1880:1880
    networks:
      iot:
    restart: unless-stopped

volumes:
  node-red-data:

networks:
  iot: