version: "3.1"

services:
  app:
    image: instantlinux/nut-upsd:latest
    restart: always
    environment:
      SERIAL: ${UPS_1_SERIAL}
      NAME: ${UPS FRIENDLY NAME}
      VENDOR ID: ${UPS VENDOR ID}
      API_PASSWORD: ${API PASSWORD}
      DESCRIPTION: ${UPS DESCRIPTION}
    ports:
    - 3493:3493
    privileged: true
