name: joinApps.sh

on:
  push:
    branches:
    - "*"
  #schedule:
  #- cron:  '15 0 * * *'

jobs:
  run_joinApps:
    name: Run joinApps.sh script
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cardinalby/export-env-action@v1
      with:
        envFile: 'build/env.sh'  
    - name: Joining Apps
      run: build/joinApps.sh
    - name: Generate App List
      run: build/generators/generateAppList.sh
    - name: Generate Doc List
      run: build/generators/generateDocList.sh
    - name: Generate README
      run: build/generators/generateREADME.sh
    - name: Generate README Tools
      run: build/generators/generateToolsREADME.sh
    - name: Commit files
      run: |
        git config --local user.email "workflow@github.com"
        git config --local user.name "GitHub Workflow"
        git add -- "$pt32"
        git add -- "$pt64"
        git add ./pi-hosted_template/template/portainer-v2.json
        git add -- "$README"
	      git add -- "$TOOLSREADME"
	      git add -- "$AppList"
	      git add -- "$DocList"
        git commit -m "Build App list and docs" || echo "No new apps detected"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
        branch: ${{ github.ref }}
